name: Check Markdown links

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@master
      with:
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/mlc_config.json'
        folder-path: 'docs/'